main: com.thefishnextdoor.jump.DoubleJump
name: DoubleJump
version: 1.0.0
api-version: 1.15
author: TheFishNextDoor
description: Jump then jump again
commands:
  doublejump:
    description: Toggle double jump
    usage: /doublejump [enable|disable]
    permission: doublejump.use
    aliases:
    - jump
permissions:
  doublejump.use:
    description: Use the double jump ability
  doublejump.reload:
    description: Reload the configuration